#!/usr/bin/env node
/**
 * scripts/sync-strings.js
 *
 * `sync-design.js` keeps the demo's *tokens and fonts* honest. It says nothing about the demo's
 * *copy* — which strings it shows, in what order, on which tabs. Those are hand-written in
 * `demo.js`, so an app change to them drifts the demo silently.
 *
 * That is not hypothetical. Renaming `Check Ripeness` in `app_en.arb`, or reordering the parcel
 * screen's tabs, leaves `sync-design --check`, the unit suite and the whole e2e suite green while
 * the demo goes on serving the old string. Nothing in the repository compared the two.
 *
 * This closes that gap. It reads the app's Dart and ARB and writes `design/app-ui.json` — a
 * manifest of tab order, stage names, bucket names and the copy the demo renders. It is generated,
 * committed, and `--check`-able. `tests/e2e/app-parity.spec.js` then renders the real demo and
 * compares that manifest against what the browser actually shows.
 *
 * Between them the two halves catch the two different failures:
 *   manifest stale            -> `--check` fails: the app changed and nobody re-derived it
 *   manifest fresh, demo drift -> the spec fails: the demo no longer matches the app
 *
 * Every pattern here fails loudly rather than degrading. A Dart refactor that moves a literal
 * somewhere this cannot see is exactly the drift worth catching, and a quiet empty section would
 * report "no drift" instead.
 *
 *   node scripts/sync-strings.js           # verify + write
 *   node scripts/sync-strings.js --check   # fail if the manifest is stale
 */
import fs from 'node:fs';
import path from 'node:path';

const APP_DIR = process.env.ZITOUNA_APP_DIR || '/home/mohamed/Desktop/Github/Zitouna';
const SITE = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const CHECK = process.argv.includes('--check');
const OUT = 'design/app-ui.json';

const read = (rel) => fs.readFileSync(path.join(APP_DIR, rel), 'utf8');
const log = (m) => process.stdout.write(m + '\n');

const BANNER =
  `/* GENERATED by scripts/sync-strings.js from the Zitouna app repo.\n` +
  `   Do not edit by hand — run \`node scripts/sync-strings.js\`. */\n`;

if (!fs.existsSync(APP_DIR)) {
  console.error(
    `[sync-strings] App repo not found at ${APP_DIR}.\n` +
    `                Set ZITOUNA_APP_DIR to the Zitouna checkout, or clone it alongside this repo.`
  );
  process.exit(1);
}

/**
 * One ARB value, or a hard failure. ARB is JSON with `@key` metadata blocks interleaved, so the
 * value is read by parsing rather than by regex — a regex here would also match the key inside a
 * placeholder spec and quietly return the wrong string.
 */
const arb = JSON.parse(read('lib/l10n/app_en.arb'));
const need = (key, why) => {
  const v = arb[key];
  if (typeof v !== 'string') {
    throw new Error(`app_en.arb: no string for "${key}" (${why})`);
  }
  return v;
};

/* ------------------------------------------------------------------ tabs */

/* The parcel screen's tab bar, read from the widget that builds it rather than from the ARB alone:
 * the ARB has all five strings, but only the screen knows that these five are the tabs and that
 * this is their order. Taking the list from the ARB would let a string that is not a tab — a
 * screen title, an error — be mistaken for one. */
log('[sync-strings] parcel tabs');
const SCREEN_FILE = 'lib/screens/parcel_detail_screen.dart';
const screenSrc = read(SCREEN_FILE);

const tabBlock = screenSrc.match(/l10n\.(tabOverview)([\s\S]*?)l10n\.tabYears,/);
if (!tabBlock) throw new Error(`${SCREEN_FILE}: could not find the tab label list`);
const tabOrder = ['tabOverview', 'tabRipeness', 'tabHarvest', 'tabMill', 'tabYears'].filter(
  (k) => tabBlock[0].includes(`l10n.${k}`)
);
if (tabOrder.length !== 5) {
  throw new Error(`${SCREEN_FILE}: expected 5 parcel tabs, found ${tabOrder.length}: ${tabOrder}`);
}
const tabs = tabOrder.map((key) => ({ key, label: need(key, `parcel tab ${key}`) }));

/* ------------------------------------------------------------------ stages and buckets */

log('[sync-strings] ripeness stages');
/* The four stages, in the app's enum order. `RipenessGauge` is declared in enums.dart, so the
 * order comes from there: the ARB alone cannot say which stage is which index. */
const enumsSrc = read('lib/data/models/enums.dart');
const gaugeEnum = enumsSrc.match(/enum RipenessGauge\s*\{([\s\S]*?)\}/);
if (!gaugeEnum) throw new Error('enums.dart: no `enum RipenessGauge`');
const stageOrder = gaugeEnum[1]
  .split(',')
  .map((s) => s.trim())
  .filter((s) => /^[a-zA-Z]/.test(s));
if (stageOrder.length !== 4) {
  throw new Error(`enums.dart: expected 4 RipenessGauge values, found ${stageOrder.length}`);
}
const STAGE_KEY = { tooEarly: 'stageTooEarly', soon: 'stageSoon', pickNow: 'stagePickNow', gettingLate: 'stageGettingLate' };
const stages = stageOrder.map((name) => {
  const key = STAGE_KEY[name];
  if (!key) throw new Error(`enums.dart: unmapped RipeningGauge value "${name}" — add it to STAGE_KEY`);
  return { name, key, label: need(key, `stage ${name}`) };
});

log('[sync-strings] ripeness buckets');
const BUCKET_KEY = { green: 'bucketGreen', turning: 'bucketTurning', purple: 'bucketPurple', black: 'bucketBlack' };
const buckets = Object.entries(BUCKET_KEY).map(([name, key]) => ({
  name,
  key,
  label: need(key, `bucket ${name}`),
}));

/* ------------------------------------------------------------------ demo copy */

log('[sync-strings] demo copy');
/**
 * The strings the demo renders, each traced to the ARB key it must equal. A key whose demo text
 * differs is not a warning — it is drift, and it is meant to fail.
 */
const copy = {
  parcelTabsLabel: need('tabOverview', 'section label'),
  checkRipeness: need('checkRipeness', 'overview card label'),
  overviewRipenessCaption: need('overviewRipenessCaption', 'overview caption template'),
  millCardTitle: need('millLog', 'overview mill card title'),
  overviewMillCaption: need('overviewMillCaption', 'overview mill card caption template'),
  noMillLogs: need('noMillLogs', 'overview mill card empty state'),
  alternateBearingTitle: need('alternateBearingTitle', 'overview forecast card title'),
  alternateBearingInsufficient: need('alternateBearingInsufficient', 'forecast empty state'),
  cameraGuide: need('cameraGuide', 'ripeness hint card'),
  saveRipenessCheck: need('saveRipenessCheck', 'ripeness save button'),
  ripenessSaved: need('ripenessSaved', 'ripeness save toast'),
  sampleTotal: need('sampleTotal', 'counter total template'),
  computedRendementLabel: need('computedRendementLabel', 'mill result label'),
  saveMillLog: need('saveMillLog', 'mill save button'),
  millLogSaved: need('millLogSaved', 'mill save toast'),
  oilReceived: need('oilReceived', 'mill oil field label'),
  deliveredInUnit: need('deliveredInUnit', 'mill olives field label template'),
  // Harvest tab
  addHarvestEntry: need('addHarvestEntry', 'harvest form title'),
  harvestDate: need('harvestDate', 'harvest date label'),
  laborPeople: need('laborPeople', 'harvest pickers label'),
  laborHours: need('laborHours', 'harvest hours label'),
  notes: need('notes', 'harvest notes label'),
  saveHarvestLog: need('saveHarvestLog', 'harvest save button'),
  harvestSaved: need('harvestSaved', 'harvest save toast'),
  seasonTotalHarvest: need('seasonTotalHarvest', 'season total template'),
  prePressEstimateTitle: need('prePressEstimateTitle', 'estimate card title'),
  prePressEstimateSubtitle: need('prePressEstimateSubtitle', 'estimate card subtitle'),
  prePressFromKg: need('prePressFromKg', 'estimate caption template'),
  noHarvestLogs: need('noHarvestLogs', 'harvest empty state'),
  // Mill tab (extended)
  addMillEntry: need('addMillEntry', 'mill form title'),
  millName: need('millName', 'mill name label'),
  oilUnit: need('oilUnit', 'mill oil unit label'),
  unitLiters: need('unitLiters', 'litres unit option'),
  unitKilograms: need('unitKilograms', 'kilograms unit option'),
  paymentType: need('paymentType', 'mill payment label'),
  paymentCash: need('paymentCash', 'cash payment option'),
  paymentShare: need('paymentShare', 'share payment option'),
  paymentMixed: need('paymentMixed', 'mixed payment option'),
  rendementComparisonTitle: need('rendementComparisonTitle', 'mill comparison title'),
  comparisonVsPriorYear: need('comparisonVsPriorYear', 'prior-year comparison label'),
  comparisonVsEstimate: need('comparisonVsEstimate', 'estimate comparison label'),
  // Years tab
  yearOverview: need('yearOverview', 'years screen title'),
  metricOil: need('metricOil', 'oil metric label'),
  avgRipenessHarvest: need('avgRipenessHarvest', 'avg ripeness label'),
  noYearlyData: need('noYearlyData', 'years empty state'),
  yearlyBreakdown: need('yearlyBreakdown', 'yearly breakdown title'),
  alternateBearingLow: need('alternateBearingLow', 'lighter-year forecast template'),
  alternateBearingHigh: need('alternateBearingHigh', 'heavier-year forecast template'),
  alternateBearingNeutral: need('alternateBearingNeutral', 'balanced-year forecast template'),
  // My Trees + parcel creation
  myTrees: need('myTrees', 'trees screen title'),
  treesCountLabel: need('treesCountLabel', 'tree count template'),
  noParcels: need('noParcels', 'trees empty state'),
  addParcel: need('addParcel', 'add parcel button'),
  createParcel: need('createParcel', 'create parcel button'),
  parcelName: need('parcelName', 'parcel name label'),
  treeCount: need('treeCount', 'tree count label'),
  variety: need('variety', 'variety label'),
  save: need('save', 'generic save'),
  cancel: need('cancel', 'generic cancel'),
  // Settings
  settingsTitle: need('settingsTitle', 'settings screen title'),
  settingsSectionUnits: need('settingsSectionUnits', 'units section header'),
  settingsSectionData: need('settingsSectionData', 'data section header'),
  settingsSectionApp: need('settingsSectionApp', 'app section header'),
  unitsTitle: need('unitsTitle', 'units title'),
  weightUnitKilograms: need('weightUnitKilograms', 'kilograms option'),
  weightUnitQuintals: need('weightUnitQuintals', 'quintals option'),
  languageTitle: need('languageTitle', 'language title'),
  homeSubtitle: need('homeSubtitle', 'My Trees header subtitle template'),
  // Known gaps: present in the app, intentionally not ported to the demo.
  backupExport: need('backupExport', 'backup export button (gap: needs a filesystem)'),
  backupImport: need('backupImport', 'backup import button (gap: needs a filesystem)'),
  shareApp: need('shareApp', 'share app button (gap: needs the installed APK)'),
  mapMode: need('mapMode', 'map parcel mode (gap: needs network tiles)'),
  languagePicker: need('languageTitle', 'language picker (gap: demo ships English only)'),
};

/* ------------------------------------------------------------------ manifest */

const manifest = {
  _comment:
    'GENERATED by scripts/sync-strings.js from the Zitouna app repo. Do not edit by hand.\n' +
    'Asserted against the running demo by tests/e2e/app-parity.spec.js.',
  tabs,
  stages,
  buckets,
  copy,
};

const json = JSON.stringify(manifest, null, 2) + '\n';

/** Writes `content` only when it differs; in --check mode records staleness instead. */
function put(destRel, content) {
  const dest = path.join(SITE, destRel);
  const existed = fs.existsSync(dest);
  const same = existed && fs.readFileSync(dest, 'utf8') === content;
  if (same) {
    log(`  = ${destRel} (up to date)`);
    return;
  }
  if (CHECK) {
    stale.push(destRel);
    return;
  }
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.writeFileSync(dest, content);
  log(`  ${existed ? '~' : '+'} ${destRel}`);
}

const stale = [];

put(OUT, json);

/* The same manifest, emitted as a script rather than fetched as JSON: the demo needs it
 * synchronously, before it paints its first tab, and a fetch would mean the page renders the
 * wrong strings and then corrects itself. */
put(
  'src/app-ui.js',
  `${BANNER}window.ZITOUNA_UI = ${JSON.stringify(
    { tabs, stages, buckets, copy },
    null,
    2
  )};\n`
);

if (CHECK && stale.length) {
  console.error(
    `\n[sync-strings] ${stale.length} generated file(s) out of date:\n` +
      stale.map((f) => `  - ${f}`).join('\n') +
      `\n\nRun \`node scripts/sync-strings.js\` and commit the result, then reconcile the demo\n` +
      `against it — tests/e2e/app-parity.spec.js will tell you what moved.\n`
  );
  process.exit(1);
}

log('\n[sync-strings] up to date.');
