#!/usr/bin/env node
/**
 * scripts/sync-design.js
 *
 * Pulls the demo's design inputs out of the Zitouna Flutter repository, so the web demo
 * tracks the app instead of a hand-copy of it.
 *
 * The app exports its design system as Dart:
 *   lib/theme/zitouna_theme.dart   ZitounaTheme.light / .dark — every colour and radius
 *   assets/fonts/*.ttf             Zilla Slab + Manrope, the families the app asks for
 *
 * Everything this writes is generated. Nothing here invents a value: if the file it reads is
 * missing, or a literal it needs cannot be found, it fails loudly rather than falling back to a
 * guess — a silent fallback is exactly how a demo drifts away from the app while still looking
 * plausible.
 *
 *   node scripts/sync-design.js            # verify + write
 *   node scripts/sync-design.js --check    # fail if anything is stale (for CI)
 */
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { tmpdir } from 'node:os';

const APP_DIR = process.env.ZITOUNA_APP_DIR || '/home/mohamed/Desktop/Github/Zitouna';
const SITE = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const CHECK = process.argv.includes('--check');

const BANNER = (src) =>
  `/* GENERATED by scripts/sync-design.js from ${src} in the Zitouna app repo.\n` +
  `   Do not edit by hand — run \`node scripts/sync-design.js\`. */\n`;

const read = (rel) => fs.readFileSync(path.join(APP_DIR, rel), 'utf8');


const dirty = [];
const log = (m) => process.stdout.write(m + '\n');

/** Writes `content` only when it differs, and reports the outcome. */
function put(destRel, content) {
  const dest = path.join(SITE, destRel);
  const existed = fs.existsSync(dest);
  const same = existed
    ? Buffer.isBuffer(content)
      ? fs.readFileSync(dest).equals(content)
      : fs.readFileSync(dest, 'utf8') === content
    : false;
  if (same) {
    log(`  = ${destRel} (up to date)`);
    return 'same';
  }
  if (CHECK) {
    dirty.push(destRel);
    return 'stale';
  }
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.writeFileSync(dest, content);
  log(`  ${existed ? '~' : '+'} ${destRel}`);
  return existed ? 'updated' : 'created';
}

if (!fs.existsSync(APP_DIR)) {
  console.error(
    `[sync-design] App repo not found at ${APP_DIR}.\n` +
    `               Set ZITOUNA_APP_DIR to the Zitouna checkout, or clone it alongside this repo.`
  );
  process.exit(1);
}

/* ------------------------------------------------------------------ tokens */

/** The `static const ZitounaTheme light = ZitounaTheme( … );` body. */
function themeBody(src, name) {
  const m = src.match(
    new RegExp(`static const ZitounaTheme ${name} = ZitounaTheme\\(([\\s\\S]*?)\\n  \\);`)
  );
  if (!m) throw new Error(`could not find \`static const ZitounaTheme ${name}\` in zitouna_theme.dart`);
  return m[1];
}

/**
 * One token, or a hard failure. The Dart writes colours as `paper: Color(0xFFF5F1E2)` —
 * eight digits, alpha first. CSS wants six, so the alpha byte is dropped only after checking it
 * is fully opaque; a translucent token would silently change meaning if it were sliced off.
 */
function color(body, field, file) {
  const m = body.match(new RegExp(`\\b${field}:\\s*Color\\(0x([0-9A-Fa-f]{2})([0-9A-Fa-f]{6})\\)`));
  if (!m) throw new Error(`zitouna_theme.dart: no opaque Color literal for \`${field}\``);
  if (m[1] !== 'FF') {
    throw new Error(
      `zitouna_theme.dart: \`${field}\` has alpha 0x${m[1]}, not FF. ` +
        `This generator only emits opaque colours; a translucent token needs a decision, not a guess.`
    );
  }
  return `#${m[2]}`;
}

/** A radius, e.g. `radiusMd = 18.0`. */
function radius(src, field, file) {
  const m = src.match(new RegExp(`this\\.${field} = ([0-9.]+)`));
  if (!m) throw new Error(`zitouna_theme.dart: no default for \`${field}\``);
  return m[1].replace(/\.0+$/, '');
}

/**
 * The demo's variable names, and the Dart field each comes from. Keeping the mapping explicit
 * here — rather than deriving names by lowercasing the Dart fields — is what lets the demo use
 * short names (`--c0`, `--raised`) while the app keeps descriptive ones (`stageEarly`,
 * `paperRaised`). A rename in the app therefore fails loudly instead of silently repointing a
 * demo variable at a different colour.
 */
const MAP = [
  ['--paper', 'paper'],
  ['--raised', 'paperRaised'],
  ['--sunken', 'paperSunken'],
  ['--ink', 'ink'],
  ['--soft', 'inkSoft'],
  ['--faint', 'inkFaint'],
  ['--line', 'line'],
  ['--lineStrong', 'lineStrong'],
  ['--olive', 'olive'],
  ['--oliveDeep', 'oliveDeep'],
  ['--oliveT', 'oliveTint'],
  ['--oliveSoft', 'oliveSoft'],
  ['--gold', 'gold'],
  ['--goldT', 'goldTint'],
  ['--c0', 'stageEarly'],
  ['--t0', 'stageEarlyTint'],
  ['--c1', 'stageSoon'],
  ['--t1', 'stageSoonTint'],
  ['--c2', 'stagePick'],
  ['--t2', 'stagePickTint'],
  ['--c3', 'stageLate'],
  ['--t3', 'stageLateTint'],
  ['--danger', 'danger'],
  ['--dangerT', 'dangerTint'],
];

const THEME_SRC = 'lib/theme/zitouna_theme.dart';
log('[sync-design] tokens');
const themeSrc = read(THEME_SRC);

const block = (name) => {
  const body = themeBody(themeSrc, name);
  return MAP.map(([cssName, field]) => `${cssName}:${color(body, field, THEME_SRC)}`).join(';');
};

// The demo reads the radii from the app so a radius change cannot leave the demo behind.
// `radiusLgHero` -> `--r-lg-hero`: the leading capital is dropped along with the `radius`
// prefix, otherwise the kebab-case split leaves a doubled dash.
const kebab = (s) =>
  s
    .replace(/^radius/, '')
    .replace(/^([A-Z])/, (c) => c.toLowerCase())
    .replace(/([A-Z])/g, '-$1')
    .toLowerCase();

const radii = ['radiusLgHero', 'radiusLg', 'radiusMd', 'radiusSm', 'radiusPill']
  .map((f) => `--r-${kebab(f)}:${radius(themeSrc, f, THEME_SRC)}px`)
  .join(';');

const tokens = `${BANNER(THEME_SRC)}
/* Light theme: the app's ZitounaTheme.light, verbatim. */
.app{${block('light')};${radii}}
/* Dark theme: the app's ZitounaTheme.dark, verbatim. */
@media(prefers-color-scheme:dark){.app{${block('dark')}}}
`;
put('src/demo-tokens.css', tokens);

/* ------------------------------------------------------------------ fonts */

/* The demo asks for Zilla Slab (display) and Manrope (UI). Without the app's own files it renders
 * in a system serif, so the type is not the app's type. The app ships .ttf; the site serves .woff2,
 * so the bytes are converted rather than copied — serving TTF bytes under a .woff2 name would be
 * rejected by the browser at runtime and is exactly the kind of quiet breakage to rule out here. */
log('[sync-design] fonts');

const WOFF2 = process.env.WOFF2_COMPRESS || 'woff2_compress';
const mkdtempSync = (p) => fs.mkdtempSync(p);

function toWoff2(rel) {
  const tmp = mkdtempSync(path.join(tmpdir(), 'zitouna-font-'));
  const staged = path.join(tmp, path.basename(rel));
  fs.copyFileSync(path.join(APP_DIR, rel), staged);
  try {
    execFileSync(WOFF2, [staged], { stdio: 'ignore' });
  } catch (e) {
    throw new Error(
      `could not run \`${WOFF2}\` to convert ${rel}.\n` +
        `               Install it (Debian/Ubuntu: apt install woff2, Arch: pacman -S woff2) or set\n` +
        `               WOFF2_COMPRESS to its path. Not converting would mean serving TTF bytes\n` +
        `               under a .woff2 name.`
    );
  }
  const out = staged.replace(/\.ttf$/, '.woff2');
  if (!fs.existsSync(out)) throw new Error(`${WOFF2} produced no .woff2 for ${rel}`);
  return fs.readFileSync(out);
}

for (const [src, dest] of [
  ['ZillaSlab-Medium.ttf', 'ZillaSlab-Medium.woff2'],
  ['ZillaSlab-Bold.ttf', 'ZillaSlab-Bold.woff2'],
  ['Manrope-Regular.ttf', 'Manrope-Regular.woff2'],
  ['Manrope-Bold.ttf', 'Manrope-Bold.woff2'],
]) {
  put(`src/fonts/${dest}`, toWoff2(`assets/fonts/${src}`));
}

/* ------------------------------------------------------------------ report */

if (CHECK && dirty.length) {
  console.error(
    `\n[sync-design] ${dirty.length} generated file(s) out of date:\n` +
      dirty.map((f) => `  - ${f}`).join('\n') +
      `\n\nRun \`node scripts/sync-design.js\` and commit the result.\n`
  );
  process.exit(1);
}

log('\n[sync-design] up to date.');
