// Demo of the app: My Trees, the parcel screen (all five tabs), and settings.
// Rules come from logic.js (ported from the app); gauge geometry from
// ripeness_arc_gauge.dart. Every user-visible string comes from window.ZITOUNA_UI,
// generated by scripts/sync-strings.js from the app's app_en.arb and
// parcel_detail_screen.dart. Nothing below is a hand-typed label.
import { ripeness, rendement, estimate, weightedRendement, bearing, toQ } from './logic.js';
import { gaugeSvg as gauge } from './gauge.js';
const UI = window.ZITOUNA_UI;
if (!UI) throw new Error("app-ui.js did not load: the demo cannot render the app's strings");
const $ = (s, r = document) => r.querySelector(s);
const STAGES = UI.stages.map((s) => s.label);
const BUCKET_KEYS = ['g', 't', 'p', 'b'];
const BUCKETS = BUCKET_KEYS.map((k, i) => [k, UI.buckets[i].label, i]);
const TABS = UI.tabs.map((t) => [t.key.replace(/^tab/, '').toLowerCase(), t.label]);
/** Fills `{name}` placeholders from the app's ARB templates. */
const fill = (tpl, vars) => tpl.replace(/\{(\w+)\}/g, (m, k) => (k in vars ? String(vars[k]) : m));
// Demo state: one example parcel with two seasons of history, so Years,
// forecasts and comparisons have something to show. Nothing persists.
const Y = new Date().getFullYear();
function seedParcel() {
  return {
    id: 'demo', name: 'Near the well', variety: 'Chemlali', trees: 25,
    c: { g: 0, t: 0, p: 0, b: 0 },
    checks: [
      { ...ripeness({ g: 8, t: 22, p: 14, b: 6 }), date: 'Sep' },
      { ...ripeness({ g: 18, t: 20, p: 8, b: 4 }), date: 'Aug' },
    ],
    harvest: [
      { date: `${Y - 1}-11-12`, kg: 380, note: 'East row' },
      { date: `${Y - 1}-11-19`, kg: 280 },
      { date: `${Y - 2}-11-10`, kg: 310 },
      { date: `${Y - 2}-11-17`, kg: 220 },
    ],
    mill: [
      { date: `${Y - 1}-11-25`, name: 'Cooperative El Baraka', kg: 430, oil: 72 },
      { date: `${Y - 2}-11-24`, name: 'Cooperative El Baraka', kg: 530, oil: 92 },
    ],
  };
}
const st = {
  screen: 'trees', tab: 'overview', parcel: null,
  parcels: [seedParcel()],
  unit: 'kg', kg: '', l: '',
};
const chip = (s) => `<span class="chip k${s}">${STAGES[s]}</span>`;
const today = () => new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'short' });
const disp = (kg) => st.unit === 'q' ? `${toQ(kg).toFixed(1)} q` : `${kg} kg`;
const P = () => st.parcels.find((p) => p.id === st.parcel);
const seasonTotal = (p, y) => p.harvest.filter((h) => new Date(h.date).getFullYear() === y).reduce((s, h) => s + h.kg, 0);
const yearKgPerTree = (p, y) => { const t = seasonTotal(p, y); return t > 0 ? t / p.trees : 0; };
const millAvg = (p) => weightedRendement(p.mill.map((m) => ({ kg: m.kg, oil: m.oil })));
const lastCheck = (p) => p.checks[p.checks.length - 1];
const MILL_PREFIX = UI.copy.overviewMillCaption.split(' ·')[0];

const views = {
  trees() {
    const cards = st.parcels.map((p) => {
      const l = lastCheck(p);
      return `<button class="pcel open" data-p="${p.id}"><span class="prow">${l ? chip(l.stage) : '<span class="dash"></span>'}<span class="chev" aria-hidden="true">›</span></span>
<p class="pn">${p.name}</p><p class="ps">${p.variety} · ${fill(UI.copy.treesCountLabel, { count: p.trees })}</p>${gauge(l ? l.index : 0, true)}</button>`;
    }).join('');
    return `<div class="thead"><div><b>${UI.copy.myTrees}</b><span>${fill(UI.copy.homeSubtitle, { treeCount: st.parcels.reduce((s, p) => s + p.trees, 0), parcelCount: st.parcels.length })}</span></div>
<div class="acts"><button class="act" id="go-set" aria-label="${UI.copy.settingsTitle}">⚙</button></div></div>${cards}
<button class="save" id="addp">${UI.copy.addParcel}</button>`;
  },
  overview() {
    const p = P(), l = lastCheck(p);
    const mill = p.mill[0];
    const yrs = [...new Set(p.harvest.map((h) => new Date(h.date).getFullYear()))].sort().reverse();
    const sig = yrs.length >= 2 ? bearing(yearKgPerTree(p, yrs[0]), yrs.slice(1).map((y) => yearKgPerTree(p, y))) : 0;
    const forecast = sig === 0 ? UI.copy.alternateBearingInsufficient
      : fill(sig < 0 ? UI.copy.alternateBearingLow : UI.copy.alternateBearingHigh, { year: yrs[0], nextYear: yrs[0] + 1 });
    return `<section class="card big"><div class="row"><span class="lbl">${UI.copy.checkRipeness}</span>${l ? chip(l.stage) : '<span class="dash"></span>'}</div>${gauge(l ? l.index : 0, true)}
<p class="cap">${fill(UI.copy.overviewRipenessCaption, { count: p.checks.length, date: l ? l.date : '—' })}</p></section>
<section class="card"><p class="v">${mill ? weightedRendement([{ kg: mill.kg, oil: mill.oil }]).toFixed(2) + ' %' : '—'}</p><p class="t">${UI.copy.millCardTitle}</p><p class="cap">${mill ? `${MILL_PREFIX} · ${mill.name}` : UI.copy.noMillLogs}</p></section>
<section class="card"><p class="t">${UI.copy.alternateBearingTitle}</p><p>${forecast}</p></section>`;
  },
  ripeness() {
    return `<section class="card hint"><div class="hintrow"><span class="ic" aria-hidden="true">◉</span><p class="t">${UI.copy.cameraGuide}</p><button class="x" id="hint-x" aria-label="Dismiss">×</button></div></section><section class="card big"><div id="g" aria-hidden="true"></div><div class="read" aria-hidden="true"><span id="chip"></span><p class="idx"><b id="idx"></b> <small>/ 7.00</small></p></div><p class="sr" id="sum" role="status"></p></section>
${BUCKETS.map(([k, n, s]) => `<div class="ctr"><i class="dot d${s}"></i><span class="cl">${n}</span><button class="rb" data-k="${k}" data-d="-1" aria-label="Remove one ${n} olive">−</button><output id="n-${k}" aria-label="${n} count">0</output><button class="rb" data-k="${k}" data-d="1" aria-label="Add one ${n} olive">+</button><button class="rb five" data-k="${k}" data-d="5" aria-label="Add five ${n} olives">+5</button></div>`).join('')}
<button class="save" id="save">${UI.copy.saveRipenessCheck}</button>`;
  },
  harvest() {
    const p = P(), y = Y, total = seasonTotal(p, y);
    const l = lastCheck(p), avg = millAvg(p);
    const e = estimate(total, 'chemlali', l ? l.index : null, avg);
    const rows = p.harvest.filter((h) => new Date(h.date).getFullYear() === y)
      .map((h) => `<div class="row"><span>${h.date}</span><b>${disp(h.kg)}</b></div>`).join('');
    return `<section class="card"><p class="t">${fill(UI.copy.seasonTotalHarvest, { year: y })}</p><p class="v">${disp(total)}</p></section>
<section class="card"><p class="t">${UI.copy.prePressEstimateTitle}</p><p class="cap">${UI.copy.prePressEstimateSubtitle}</p>
<p class="v">${e.oilLo}–${e.oilHi} L</p><p class="cap">${fill(UI.copy.prePressFromKg, { kg: total })}</p></section>
<section class="card"><p class="t">${UI.copy.addHarvestEntry}</p>
<label class="f">${UI.copy.harvestDate}<input id="h-date" type="date" value="${new Date().toISOString().slice(0, 10)}"></label>
<label class="f">${st.unit === 'q' ? 'Harvested (q)' : 'Harvested (kg)'}<input id="h-kg" type="number" inputmode="decimal" min="0"></label>
<button class="save" id="h-save">${UI.copy.saveHarvestLog}</button></section>
<section class="card">${rows || `<p class="cap">${UI.copy.noHarvestLogs}</p>`}</section>`;
  },
  mill() {
    const p = P();
    const rows = p.mill.map((m) => {
      const pct = weightedRendement([{ kg: m.kg, oil: m.oil }]);
      return `<div class="row"><span>${m.date} · ${m.name}</span><b>${pct.toFixed(2)} %</b></div>`;
    }).join('');
    return `<section class="card"><p class="t">${UI.copy.addMillEntry}</p>
<label class="f">${UI.copy.millName}<input id="m-name" type="text"></label>
<label class="f">${fill(UI.copy.deliveredInUnit, { unit: 'kg' })}<input id="kg" type="number" inputmode="decimal" min="0" value="${st.kg}"></label>
<label class="f">${UI.copy.oilReceived}<input id="l" type="number" inputmode="decimal" min="0" value="${st.l}"></label>
<p class="cap">${UI.copy.computedRendementLabel}</p><p class="v" id="rd" aria-live="polite">—</p><p class="cap" id="wk">Enter both amounts.</p></section>
<button class="save" id="save">${UI.copy.saveMillLog}</button>
<section class="card">${rows || `<p class="cap">${UI.copy.noMillLogs}</p>`}</section>`;
  },
  years() {
    const p = P();
    const yrs = [...new Set([...p.harvest, ...p.mill].map((e) => new Date(e.date).getFullYear()))].sort().reverse();
    const cards = yrs.map((y) => {
      const t = seasonTotal(p, y);
      const oil = p.mill.filter((m) => new Date(m.date).getFullYear() === y).reduce((s, m) => s + m.oil * 0.916, 0);
      const avg = p.checks.length ? (p.checks.reduce((s, c) => s + c.index, 0) / p.checks.length).toFixed(1) : '—';
      return `<section class="card"><p class="t">${y}</p><p>${UI.copy.metricOil}: ${oil.toFixed(0)} L · ${disp(t)}</p><p class="cap">${UI.copy.avgRipenessHarvest}: ${avg} / 7.0</p></section>`;
    }).join('');
    const sig = yrs.length >= 2 ? bearing(yearKgPerTree(p, yrs[0]), yrs.slice(1).map((y) => yearKgPerTree(p, y))) : 0;
    const forecast = sig === 0 ? UI.copy.alternateBearingInsufficient
      : fill(sig < 0 ? UI.copy.alternateBearingLow : UI.copy.alternateBearingHigh, { year: yrs[0], nextYear: yrs[0] + 1 });
    return `<section class="card"><p class="t">${UI.copy.yearOverview}</p><p class="cap">${UI.copy.yearlyBreakdown}</p></section>
<section class="card"><p class="t">${UI.copy.alternateBearingTitle}</p><p>${forecast}</p></section>${cards || `<section class="card"><p class="cap">${UI.copy.noYearlyData}</p></section>`}`;
  },
  settings() {
    return `<section class="card"><p class="t">${UI.copy.settingsSectionUnits}</p><p class="t">${UI.copy.unitsTitle}</p>
<div class="row"><button class="rb" data-u="kg" aria-pressed="${st.unit === 'kg'}">${UI.copy.weightUnitKilograms}</button>
<button class="rb" data-u="q" aria-pressed="${st.unit === 'q'}">${UI.copy.weightUnitQuintals}</button></div></section>
<section class="card"><p class="t">${UI.copy.settingsTitle}</p><p class="cap">Zitouna demo · example data, nothing is stored.</p></section>`;
  },
};

function paintRipeness() {
  const p = P(), r = ripeness(p.c);
  $('#g').innerHTML = gauge(r.index, false); $('#chip').innerHTML = chip(r.stage); $('#idx').textContent = r.index.toFixed(2);
  $('#sum').textContent = `${STAGES[r.stage]}. Ripeness index ${r.index.toFixed(2)} of 7.00, from ${r.n} olives.`;
  for (const k in p.c) { $('#n-' + k).textContent = p.c[k]; $(`.rb[data-k=${k}][data-d="-1"]`).setAttribute('aria-disabled', !p.c[k]); }
  $('#save').setAttribute('aria-disabled', !r.n);
}
function toast(m) { const t = $('#toast'); t.textContent = ''; setTimeout(() => { t.textContent = m; }, 60); t.classList.add('on'); clearTimeout(toast.t); toast.t = setTimeout(() => t.classList.remove('on'), 2600); }

const TAB_KEYS = ['overview', 'ripeness', 'harvest', 'mill', 'years'];
function shell(title, sub, body) {
  const tabs = TABS.map(([k, l]) => `<button role="tab" id="t-${k}" aria-controls="p" data-t="${k}" aria-selected="${st.tab === k}" tabindex="${st.tab === k ? 0 : -1}">${l}</button>`).join('');
  return `<div class="app" role="group" aria-label="Zitouna app demo"><header class="abar"><button class="bk" id="bk-trees" aria-label="Back to ${UI.copy.myTrees}">‹</button><div class="tt"><b>${title}</b><span>${sub}</span></div></header>
<div class="tabs" role="tablist" aria-label="Parcel sections">${tabs}</div>
<div id="p" role="tabpanel" tabindex="0">${body}</div><div class="toast" id="toast" role="status"></div></div>`;
}
function shellTrees(body) {
  return `<div class="app" role="group" aria-label="Zitouna app demo">
<div id="p" role="tabpanel" tabindex="0">${body}</div><div class="toast" id="toast" role="status"></div></div>`;
}
function render() {
  const root = $('#demo');
  if (st.screen === 'trees') {
    root.innerHTML = shellTrees(views.trees());
    root.querySelectorAll('.open').forEach((b) => b.onclick = () => { st.parcel = b.dataset.p; st.screen = 'parcel'; st.tab = 'overview'; render(); });
    const gs = $('#go-set');
    if (gs) gs.onclick = () => { st.screen = 'settings'; render(); };
    const add = $('#addp');
    if (add) add.onclick = () => {
      const n = st.parcels.length + 1;
      st.parcels.push({ id: 'p' + Date.now(), name: `Parcel ${n}`, variety: 'Chemlali', trees: 20, c: { g: 0, t: 0, p: 0, b: 0 }, checks: [], harvest: [], mill: [] });
      render();
    };
    return;
  }
  if (st.screen === 'settings') {
    root.innerHTML = `<div class="app" role="group" aria-label="Zitouna app demo"><header class="abar"><button class="bk" id="bk-trees" aria-label="Back to ${UI.copy.myTrees}">‹</button><div class="tt"><b>${UI.copy.settingsTitle}</b></div></header><div id="p" role="tabpanel" tabindex="0">${views.settings()}</div><div class="toast" id="toast" role="status"></div></div>`;
    root.querySelectorAll('[data-u]').forEach((b) => b.onclick = () => { st.unit = b.dataset.u; render(); });
    $('#bk-trees').onclick = () => { st.screen = 'trees'; render(); };
    return;
  }
  const p = P();
  root.innerHTML = shell(p.name, `${p.variety} · ${p.trees} trees`, views[st.tab]());
  root.querySelectorAll('[role=tab]').forEach((b) => { b.onclick = () => { st.tab = b.dataset.t; render(); }; });
  bindTab(p);
  backButton(root);
}
function backButton(root) {
  $('#bk-trees').onclick = () => { st.screen = 'trees'; render(); };
}
function bindTab(p) {
  const panel = $('#p');
  if (st.tab === 'ripeness') {
    const hx = $('#hint-x');
    if (hx) hx.onclick = () => { const h = hx.closest('.card.hint'); if (h) h.remove(); };
    paintRipeness();
    panel.querySelectorAll('.rb').forEach((b) => b.addEventListener('click', () => { if (b.getAttribute('aria-disabled') === 'true') return; const k = b.dataset.k; p.c[k] = Math.max(0, p.c[k] + +b.dataset.d); paintRipeness(); }));
    $('#save').onclick = () => { const r = ripeness(p.c); if (!r.n) return; p.checks.push({ ...r, date: today() }); toast(UI.copy.ripenessSaved); render(); };
  }
  if (st.tab === 'mill') {
    const upd = () => { st.kg = $('#kg').value; st.l = $('#l').value; const kg = parseFloat($('#kg').value), l = parseFloat($('#l').value), r = rendement(kg, l);
      $('#rd').textContent = r ? r.pct.toFixed(2) + ' %' : '—'; $('#wk').textContent = r ? `${l} L × 0.916 = ${r.oil.toFixed(2)} kg of oil` : 'Enter both amounts.'; $('#save').setAttribute('aria-disabled', !r); st.pend = r; };
    $('#kg').oninput = $('#l').oninput = upd; upd();
    $('#save').onclick = () => { if (!st.pend) return; p.mill.unshift({ date: new Date().toISOString().slice(0, 10), name: $('#m-name').value || '—', kg: parseFloat($('#kg').value), oil: parseFloat($('#l').value) }); toast(UI.copy.millLogSaved); render(); };
  }
  if (st.tab === 'harvest') {
    $('#h-save').onclick = () => {
      const kg = st.unit === 'q' ? parseFloat($('#h-kg').value) * 100 : parseFloat($('#h-kg').value);
      if (!(kg > 0)) return;
      p.harvest.unshift({ date: $('#h-date').value, kg, note: '' });
      toast(UI.copy.harvestSaved); render();
    };
  }
}
const order = TAB_KEYS;
document.addEventListener('keydown', (e) => {
  if (!document.querySelector('#demo [role=tablist]')) return;
  const i = order.indexOf(st.tab);
  const n = { ArrowRight: (i + 1) % 5, ArrowLeft: (i + 4) % 5, Home: 0, End: 4 }[e.key];
  if (n !== undefined && document.activeElement && document.activeElement.getAttribute('role') === 'tab') { e.preventDefault(); st.tab = order[n]; render(); const t = $(`#t-${order[n]}`); if (t) t.focus(); }
});
render();
