// Demo of the app's parcel screen. Rules come from logic.js (ported from the app); geometry from
// ripeness_arc_gauge.dart. Every user-visible string comes from window.ZITOUNA_UI, generated by
// scripts/sync-strings.js from the app's app_en.arb and parcel_detail_screen.dart. Nothing below is
// a hand-typed label: a rename in the app reaches the demo on the next sync, and
// tests/e2e/app-parity.spec.js fails if the demo and the app disagree.
import { ripeness, rendement } from './logic.js';
import { gaugeSvg as gauge } from './gauge.js';
const UI = window.ZITOUNA_UI;
if (!UI) throw new Error("app-ui.js did not load: the demo cannot render the app's strings");
const $ = (s, r = document) => r.querySelector(s);
const STAGES = UI.stages.map((s) => s.label);
// The demo's own state keys. The app's bucket *order* and *labels* come from the manifest; these
// letters are the demo's internal shape and have no counterpart in the app.
const BUCKET_KEYS = ['g', 't', 'p', 'b'];
const BUCKETS = BUCKET_KEYS.map((k, i) => [k, UI.buckets[i].label, i]);
// The app's parcel screen has five tabs; the demo ports three. The three are taken from the
// manifest in the app's order, so a reordering upstream shows up here instead of being silently
// overridden. The two unported tabs are declared as KNOWN_GAPS in tests/e2e/app-parity.spec.js.
const PORTED_TABS = ['tabOverview', 'tabRipeness', 'tabMill'];
const TABS = UI.tabs
  .filter((t) => PORTED_TABS.includes(t.key))
  .map((t) => [t.key.replace(/^tab/, '').toLowerCase(), t.label]);
/** Fills `{name}` placeholders from the app's ARB templates. */
const fill = (tpl, vars) => tpl.replace(/\{(\w+)\}/g, (m, k) => (k in vars ? String(vars[k]) : m));
const st = { tab: 'overview', c: { g: 0, t: 0, p: 0, b: 0 }, checks: [], mill: null, kg: '', l: '' };
const chip = (s) => `<span class="chip k${s}">${STAGES[s]}</span>`;
const today = () => new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'short' });
// The app's mill card reads "Last rendement · {millName}"; the demo's example parcel has no mill
// name, so it shows the app's prefix. Deriving it from the template means a rename upstream moves
// both together.
const MILL_CAPTION = UI.copy.overviewMillCaption.split(' ·')[0];

const views = {
  overview() {
    const l = st.checks[st.checks.length - 1];
    return `<section class="card big"><div class="row"><span class="lbl">${UI.copy.checkRipeness}</span>${l ? chip(l.stage) : '<span class="dash"></span>'}</div>${gauge(l ? l.index : 0, true)}
<p class="cap">${fill(UI.copy.overviewRipenessCaption, { count: st.checks.length, date: l ? l.date : '\u2014' })}</p></section>
<section class="card"><p class="v">${st.mill ? st.mill.toFixed(2) + ' %' : '\u2014'}</p><p class="t">${UI.copy.millCardTitle}</p><p class="cap">${st.mill ? MILL_CAPTION : UI.copy.noMillLogs}</p></section>
<section class="card"><p class="t">${UI.copy.alternateBearingTitle}</p><p>${UI.copy.alternateBearingInsufficient}</p></section>`;
  },
  ripeness() {
    return `<section class="card hint"><p class="t">${UI.copy.cameraGuide}</p></section><section class="card big"><div id="g" aria-hidden="true"></div><div class="read" aria-hidden="true"><span id="chip"></span><p class="idx"><b id="idx"></b> <small>/ 7.00</small></p></div><p class="sr" id="sum" role="status"></p></section>
${BUCKETS.map(([k, n, s]) => `<div class="ctr"><i class="dot d${s}"></i><span class="cl">${n}</span><button class="rb" data-k="${k}" data-d="-1" aria-label="Remove one ${n} olive">\u2212</button><output id="n-${k}" aria-label="${n} count">0</output><button class="rb" data-k="${k}" data-d="1" aria-label="Add one ${n} olive">+</button><button class="rb five" data-k="${k}" data-d="5" aria-label="Add five ${n} olives">+5</button></div>`).join('')}
<button class="save" id="save">${UI.copy.saveRipenessCheck}</button>`;
  },
  mill() {
    return `<section class="card"><label class="f">${fill(UI.copy.deliveredInUnit, { unit: 'kg' })}<input id="kg" type="number" inputmode="decimal" min="0" value="${st.kg}"></label><label class="f">${UI.copy.oilReceived}<input id="l" type="number" inputmode="decimal" min="0" value="${st.l}"></label>
<p class="cap">${UI.copy.computedRendementLabel}</p><p class="v" id="rd" aria-live="polite">\u2014</p><p class="cap" id="wk">Enter both amounts.</p></section><button class="save" id="save">${UI.copy.saveMillLog}</button>`;
  },
};

function paintRipeness() {
  const r = ripeness(st.c);
  $('#g').innerHTML = gauge(r.index, false); $('#chip').innerHTML = chip(r.stage); $('#idx').textContent = r.index.toFixed(2);
  $('#sum').textContent = `${STAGES[r.stage]}. Ripeness index ${r.index.toFixed(2)} of 7.00, from ${r.n} olives.`;
  for (const k in st.c) { $('#n-' + k).textContent = st.c[k]; $(`.rb[data-k=${k}][data-d="-1"]`).setAttribute('aria-disabled', !st.c[k]); }
  $('#save').setAttribute('aria-disabled', !r.n);
}
function toast(m) { const t = $('#toast'); t.textContent = ''; setTimeout(() => { t.textContent = m; }, 60); t.classList.add('on'); clearTimeout(toast.t); toast.t = setTimeout(() => t.classList.remove('on'), 2600); }
function show(tab, focus) {
  st.tab = tab;
  document.querySelectorAll('#demo [role=tab]').forEach((b) => { const on = b.dataset.t === tab; b.setAttribute('aria-selected', on); b.tabIndex = on ? 0 : -1; if (on && focus) b.focus(); });
  const p = $('#p'); p.setAttribute('aria-labelledby', 't-' + tab); p.innerHTML = views[tab]();
  if (tab === 'ripeness') {
    paintRipeness();
    p.querySelectorAll('.rb').forEach((b) => b.addEventListener('click', () => { if (b.getAttribute('aria-disabled') === 'true') return; const k = b.dataset.k; st.c[k] = Math.max(0, st.c[k] + +b.dataset.d); paintRipeness(); }));
    $('#save').onclick = () => { const r = ripeness(st.c); if (!r.n) return; st.checks.push({ ...r, date: today() }); toast(UI.copy.ripenessSaved); };
  }
  if (tab === 'mill') {
    const upd = () => { st.kg = $('#kg').value; st.l = $('#l').value; const kg = parseFloat($('#kg').value), l = parseFloat($('#l').value), r = rendement(kg, l);
      $('#rd').textContent = r ? r.pct.toFixed(2) + ' %' : '\u2014'; $('#wk').textContent = r ? `${l} L \u00d7 0.916 = ${r.oil.toFixed(2)} kg of oil` : 'Enter both amounts.'; $('#save').setAttribute('aria-disabled', !r); st.pend = r; };
    $('#kg').oninput = $('#l').oninput = upd; upd();
    $('#save').onclick = () => { if (st.pend) { st.mill = st.pend.pct; toast(UI.copy.millLogSaved); } };
  }
}
const root = $('#demo');
root.innerHTML = `<div class="app" role="group" aria-label="Zitouna app demo"><header class="ah"><p class="nm">Example parcel</p><p>Chemlali \u00b7 25 trees</p></header>
<div class="tabs" role="tablist" aria-label="Parcel sections">${TABS.map(([k, l]) => `<button role="tab" id="t-${k}" aria-controls="p" data-t="${k}">${l}</button>`).join('')}</div>
<div id="p" role="tabpanel" tabindex="0"></div><div class="toast" id="toast" role="status"></div></div>`;
const order = ['overview', 'ripeness', 'mill'];
root.querySelectorAll('[role=tab]').forEach((b) => { b.onclick = () => show(b.dataset.t); b.onkeydown = (e) => { const i = order.indexOf(st.tab), n = { ArrowRight: (i + 1) % 3, ArrowLeft: (i + 2) % 3, Home: 0, End: 2 }[e.key]; if (n !== undefined) { e.preventDefault(); show(order[n], true); } }; });
show('overview');
